### ISSUE TITLE
aspect copier fails on gemoc offical sample

### ISSUE THREAD

**Issue by dvojtise** [diverse-project/melange#104]
with latest melange (2018-01-11)

generating language runtime on the official fsm example (that uses inheritance) fails

```
Exception in thread "ModalContext" org.eclipse.core.internal.resources.ResourceException: Resource '/org.eclipse.gemoc.sample.legacyfsm.xsfsm.xsfsm/src-gen/org/eclipse/gemoc/sample/legacyfsm/xsfsm/xsfsm/aspects/StateMachineAspect.java' already exists.
	at org.eclipse.core.internal.resources.Resource.checkDoesNotExist(Resource.java:314)
	at org.eclipse.core.internal.resources.Resource.checkDoesNotExist(Resource.java:301)
	at org.eclipse.core.internal.resources.File.create(File.java:107)
	at org.eclipse.core.internal.resources.File.create(File.java:181)
	at fr.inria.diverse.melange.utils.AspectCopier2$9.accept(AspectCopier2.java:367)
	at fr.inria.diverse.melange.utils.AspectCopier2$9.accept(AspectCopier2.java:1)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at fr.inria.diverse.melange.utils.AspectCopier2.copyLocalAspects(AspectCopier2.java:373)
	at fr.inria.diverse.melange.utils.AspectCopier2.copyAspect(AspectCopier2.java:174)
	at fr.inria.diverse.melange.utils.AspectCopier2.copyAspect(AspectCopier2.java:110)
	at fr.inria.diverse.melange.ast.LanguageExtensions.createExternalAspects(LanguageExtensions.java:726)
	at fr.inria.diverse.melange.ui.builder.MelangeBuilder$4.accept(MelangeBuilder.java:250)
	at fr.inria.diverse.melange.ui.builder.MelangeBuilder$4.accept(MelangeBuilder.java:1)
	at com.google.common.collect.Iterables$4.lambda$forEach$0(Iterables.java:581)
	at com.google.common.collect.Iterables$5.lambda$forEach$0(Iterables.java:624)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.google.common.collect.Iterables$5.forEach(Iterables.java:621)
	at com.google.common.collect.Iterables$4.forEach(Iterables.java:578)
	at fr.inria.diverse.melange.ui.builder.MelangeBuilder.generateLanguages(MelangeBuilder.java:289)
	at fr.inria.diverse.melange.ui.menu.GenerateLanguages$1.run(GenerateLanguages.java:63)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
```

step to reproduce:

- download version from eclipse ci (branch with melange https://ci.eclipse.org/gemoc/job/gemoc-studio/job/upgrade-melange-01-2018/ )
- import in your workspace the official sample from git (https://github.com/eclipse/gemoc-studio/tree/master/official_samples/LegacyFSM/language_workbench)
- right click on /org.eclipse.gemoc.sample.legacyfsm.xsfsm/src/org/eclipse/gemoc/sample/legacyfsm/xsfsm/language/XSFSM.melange ; generate language runtime

**Comment by dvojtise** [comment]
duplicate of #68 
this is just another symptom /stack trace resulting from Melange not being able to deal with nested projects
