### ISSUE TITLE
fr.inria.diverse.melange.resource.MelangeDerivedStateComputer  - Fatal exception on Gemoc official sample

### ISSUE THREAD

**Issue by dvojtise** [diverse-project/melange#105]
unfortunately the bug is not completely consistent

but with the latest Gemoc studio with latest melange, installing the official sample sometimes fails with the following errors: `fr.inria.diverse.melange.resource.MelangeDerivedStateComputer  - Fatal exception`
```
ava.lang.NullPointerException
	at fr.inria.diverse.melange.utils.AspectToEcore$1.apply(AspectToEcore.java:123)
	at fr.inria.diverse.melange.utils.AspectToEcore$1.apply(AspectToEcore.java:1)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at fr.inria.diverse.melange.utils.AspectToEcore.inferEcoreFragment(AspectToEcore.java:128)
	at fr.inria.diverse.melange.builder.WeaveBuilder.make(WeaveBuilder.java:96)
	at fr.inria.diverse.melange.builder.AbstractBuilder.build(AbstractBuilder.java:60)
	at fr.inria.diverse.melange.builder.LanguageBuilder$9.accept(LanguageBuilder.java:212)
	at fr.inria.diverse.melange.builder.LanguageBuilder$9.accept(LanguageBuilder.java:1)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at fr.inria.diverse.melange.builder.LanguageBuilder.make(LanguageBuilder.java:217)
	at fr.inria.diverse.melange.builder.AbstractBuilder.build(AbstractBuilder.java:60)
	at fr.inria.diverse.melange.processors.LanguageProcessor.build(LanguageProcessor.java:160)
	at fr.inria.diverse.melange.processors.LanguageProcessor.access$2(LanguageProcessor.java:154)
	at fr.inria.diverse.melange.processors.LanguageProcessor$2.accept(LanguageProcessor.java:117)
	at fr.inria.diverse.melange.processors.LanguageProcessor$2.accept(LanguageProcessor.java:1)
	at com.google.common.collect.Iterables$5.lambda$forEach$0(Iterables.java:624)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.google.common.collect.Iterables$5.forEach(Iterables.java:621)
	at fr.inria.diverse.melange.processors.LanguageProcessor._preProcess(LanguageProcessor.java:120)
	at fr.inria.diverse.melange.processors.LanguageProcessor.preProcess(LanguageProcessor.java:289)
	at fr.inria.diverse.melange.resource.MelangeDerivedStateComputer$1.accept(MelangeDerivedStateComputer.java:106)
	at fr.inria.diverse.melange.resource.MelangeDerivedStateComputer$1.accept(MelangeDerivedStateComputer.java:1)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at fr.inria.diverse.melange.resource.MelangeDerivedStateComputer.installDerivedState(MelangeDerivedStateComputer.java:110)
	at org.eclipse.xtext.resource.DerivedStateAwareResource.installDerivedState(DerivedStateAwareResource.java:242)
	at org.eclipse.xtext.xbase.resource.BatchLinkableResource.getContents(BatchLinkableResource.java:148)
	at org.eclipse.xtext.xbase.typesystem.internal.LogicalContainerAwareBatchTypeResolver.getEntryPoints(LogicalContainerAwareBatchTypeResolver.java:44)
	at org.eclipse.xtext.xbase.typesystem.internal.DefaultBatchTypeResolver.getTypeResolver(DefaultBatchTypeResolver.java:84)
	at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver$1.get(CachingBatchTypeResolver.java:49)
	at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver$1.get(CachingBatchTypeResolver.java:46)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:77)
	at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver.doResolveTypes(CachingBatchTypeResolver.java:46)
	at org.eclipse.xtext.xbase.typesystem.internal.AbstractBatchTypeResolver.resolveTypes(AbstractBatchTypeResolver.java:69)
	at org.eclipse.xtext.xbase.resource.BatchLinkingService.resolveBatched(BatchLinkingService.java:71)
	at org.eclipse.xtext.xbase.resource.BatchLinkableResource.resolveLazyCrossReferences(BatchLinkableResource.java:165)
	at org.eclipse.xtext.EcoreUtil2.resolveLazyCrossReferences(EcoreUtil2.java:498)
	at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.doUpdate(ClusteringBuilderState.java:230)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:116)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:287)
	at org.eclipse.xtext.builder.impl.XtextBuilder.fullBuild(XtextBuilder.java:319)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:155)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```
additionally,
the **inherits** fails to find the other language (see screenshot)
and strangely, the plugins dependencies seems to be broken because despite that the manifest declares *org.eclipse.gemoc.sample.legacyfsm.fsm*, the project doesn't import it (see "Plug-in Dependencies" entry in the project tree)

![image](https://user-images.githubusercontent.com/661468/36145465-ba661ea6-10b1-11e8-9a2d-67a37bb52db8.png)

**Comment by dvojtise** [comment]
Workaround:

- rename the melange file (*/org.eclipse.gemoc.sample.legacyfsm.xsfsm/src/org/eclipse/gemoc/sample/legacyfsm/xsfsm/language/XSFSM.melange*) with another extension. (I used  XSFSM.melange2 )
- Restart eclipse (I've found no way to fix it without restarting eclipse); The *org.eclipse.gemoc.sample.legacyfsm.fsm* should now appear in the Plug-in Dependencies
- rename back the melange file with the proper *melange* extension


this problem sounds like an issue about the order in which the tools are called in the builder (xtend/xext builder )
