### ISSUE TITLE
using xtext + melange may raise IllegalArgumentException: Qualified name cannot be empty

### ISSUE THREAD

**Issue by dvojtise** [diverse-project/melange#125]
```
java.lang.IllegalArgumentException: Qualified name cannot be empty
	at org.eclipse.xtext.naming.IQualifiedNameConverter$DefaultImpl.toQualifiedName(IQualifiedNameConverter.java:59)
	at org.eclipse.xtext.xbase.XbaseQualifiedNameConverter.toQualifiedName(XbaseQualifiedNameConverter.java:36)
	at fr.inria.diverse.melange.utils.MelangeQualifiedNameProvider.getFullyQualifiedName(MelangeQualifiedNameProvider.java:53)
	at fr.inria.diverse.melange.utils.MelangeQualifiedNameProvider.getFullyQualifiedName(MelangeQualifiedNameProvider.java:31)
```

the test verifies only !== null but does not verifies isEmpty

**Comment by fcoulon** [comment]
It can't retrieve the Language's name ?

**Comment by dvojtise** [comment]
on my example, the ImportDsl name is not null  but is an empty String (so it was crashing here https://github.com/diverse-project/melange/blob/master/plugins/fr.inria.diverse.melange/src/main/java/fr/inria/diverse/melange/utils/MelangeQualifiedNameProvider.xtend#L32 because it was not able to fallback to the alternative way to get the dsl name)
the example is based on xtext first (ie. the ecore is generated from xtext) then use melange to "downcast" and not using sirius.

**Comment by fcoulon** [comment]
Ok thanks for the fix

Just for info, the ImportDsl.name should be set by this preprocessor (this may be a corner case):
https://github.com/diverse-project/melange/blob/master/plugins/fr.inria.diverse.melange/src/main/java/fr/inria/diverse/melange/processors/ImportDslProcessor.xtend#L50
